### ISSUE TITLE
Access error while attempting to login to Query Builder

### ISSUE THREAD

**Issue by tkolleh** [MIT-LCP/QueryBuilder-AWS#3]
Error while attempting to login via https://querybuilder-lcp.mit.edu/ using valid credentials. Not sure if the password might be the cause. My password has special characters (@ and #) in it. Or if it's due to authorization.

```
<type 'exceptions.KeyError'> | Python 2.7.15: /usr/bin/pythonWed Mar 6 21:47:37 2019
-- | --

/var/www/vhosts/querybuilder-lcp.mit.edu/html/index.cgi in ()
--
106         </div>""")
107 if Error:
=>  108   print ("<script>bootbox.alert('{1}', function() {console.log('{2}'');});</script>".format(Error,Error))
109 print ("""<div class="panel panel-default">
110           <div class="panel-body">
Error = 'Error With the user/password'

```

**Comment by elfeto** [comment]
The error should have been fixed. I was working in moving the entire application from python cgi into a flask application, in which this should be fixed.

If a person has access for this [page](https://physionet.org/works/MIMICIIIClinicalDatabase/files/), then in theory the same should apply for this app.

Let me know if you can log in. Remember that the credentials are the same as PhysioNet.org.

**Comment by tkolleh** [comment]
I have access to `https://physionet.org/users/**********/`. However using the same credentials I do not have access to `https://physionet.org/works/MIMICIIIClinicalDatabase/files/`, linked above. I've contacted mimic support and am working to get access to the data.

Thanks for helping me get access.
